### ISSUE TITLE
Installation api/BamReader.h: No such file or directory

### ISSUE THREAD

**Issue by LucoLab** [ncbi/TPMCalculator#25]
Hi

Follow the protocol to install and get the following error when doing make in TPM calculator folder.

```
:~/bin/TPMCalculator$ make
"make" -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/jean-philippe.villemin/bin/TPMCalculator'
"make"  -f nbproject/Makefile-Release.mk bin/TPMCalculator
make[2]: Entering directory '/home/jean-philippe.villemin/bin/TPMCalculator'
mkdir -p build/Release/GNU-MacOSX/src
rm -f "build/Release/GNU-MacOSX/src/DiffExpIR.o.d"
g++ -g -I /home/jean-philippe.villemin/bin/bamtools/include  -c -O2 -Iincludes -std=c++14 -MMD -MP -MF "build/Release/GNU-MacOSX/src/DiffExpIR.o.d" -o build/Release/GNU-MacOSX/src/DiffExpIR.o src/DiffExpIR.cpp
src/DiffExpIR.cpp:26:27: fatal error: api/BamReader.h: No such file or directory
 #include "api/BamReader.h"
                           ^
compilation terminated.
nbproject/Makefile-Release.mk:92: recipe for target 'build/Release/GNU-MacOSX/src/DiffExpIR.o' failed
make[2]: *** [build/Release/GNU-MacOSX/src/DiffExpIR.o] Error 1
make[2]: Leaving directory '/home/jean-philippe.villemin/bin/TPMCalculator'
nbproject/Makefile-Release.mk:85: recipe for target '.build-conf' failed
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory '/home/jean-philippe.villemin/bin/TPMCalculator'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make: *** [.build-impl] Error
```

**Comment by r78v10a07** [comment]
Hi,
You need to compile the bamtools and create the env variables before compiling TPMCalculator.

Run this code:

```
git clone https://github.com/pezmaster31/bamtools
cd bamtools
mkdir build
cd build
cmake ..
make
cd ..
export BAMTOOLS_DIR=`pwd`
export CPPFLAGS="-I $BAMTOOLS_DIR/include"
export LDFLAGS="-L $BAMTOOLS_DIR/lib -Wl,-rpath,$BAMTOOLS_DIR/lib"
```
After doing this you can compile TPMCalculator.
Please, let me know if this help.

**Comment by LucoLab** [comment]
Yeah I did that first.
But I think pwd it's not giving the good path to access api directory then. All .h and .c are in 
/bin/bamtools/build/src/api/include/api. No include directory was created in /home/jean-philippe.villemin/bin/bamtools/.

**Comment by LucoLab** [comment]
Changed inside build/cmake_install.cmake .
`   set(CMAKE_INSTALL_PREFIX "/usr/local/") 
`to 

`   set(CMAKE_INSTALL_PREFIX "/home/jean-philippe.villemin/bin/bamtools/") 
`

That created the include and lib in bamtools dir and then TPM calculator find them.

**Comment by r78v10a07** [comment]
Good!
Let me know if I can be of any help.

**Comment by aheinzel** [comment]
In case of compiling TPMCalculator on Ubuntu with libbamtools-dev installed you can use:

> export CPPFLAGS="-I /usr/include/bamtools"
> export LDFLAGS="-L /usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu"
