### ISSUE TITLE
Compatibility with gencode GTF

### ISSUE THREAD

**Issue by LucoLab** [ncbi/TPMCalculator#28]
I know you didn't test TPMCalculator with Gencode gtf in your publication  .

That would be great if you could confirm that there no incompatibilities using gtf from Gencode.

What main difference between ucsc and gencode gtf could lead to wrong results  ?

From test I have done, it seems to work. I didn't get specific errors with human gtf v25. But still, I didn't go into details to check the counts are well done.

Thanks

**Comment by r78v10a07** [comment]
Hi,
Thank you so much for your report.
We have several reports from users that are using TPMCalculator with the Gencode GTF without any problem. I haven not tested yet but I will do some comparisons next week. I will post the results here. 
Keeping the issue open until that point.

**Comment by r78v10a07** [comment]
I finished the correlation analysis of TPMCalculator with RSeQC (FPKM), HTSeq and featureCounts in the same way we did for the TPMCalculator paper using the Gencode v25 genome annotation. A new wiki pages named Validation was added showing all plots for both genomes annotations:
https://github.com/ncbi/TPMCalculator/wiki/Validation
