### ISSUE TITLE
A critical issue: different number of genes in output for different BAM files

### ISSUE THREAD

**Issue by andreyurch** [ncbi/TPMCalculator#29]
Dear TPMCalculator team,

Thank you for a very useful tool, but I found that it produces a different number of genes for different BAM files with the same GTF file. It seems that the tool output only genes with a non-zero count. This is a wrong way  - for example, one produced 10 bam files and calculated TPMs, next week he produced another 5 BAM files and calculated TPMs for them but it is very difficult to join all these 15 TPM count files because they have a different number of lines! The genes with non-zero counts should be present in the output and should always be in the same order based on the GTF file. It makes much easy to join them with just a "paste" Linux command.

best regards,
Andrey

**Comment by r78v10a07** [comment]
Hi Andrey,
Thank you for your suggestion. We decided to print out only genes with counts in order to keep the output sizes as low as possible. However, I can understand that some users would like to have a full list of genes for post-processing scripts.

I will add a new option to print out all genes sorted by chromosome and starting position.

I would like to share with you a python code snippet we use to merge TPMCalculator outputs from different BAM files. It uses Pandas and it is very efficient.  
  
```python
import os
import pandas

if __name__ == '__main__':
    # TPMCalculator column to extract
    column = "ExonTPM"

    # TPMCalculator output directory
    TPMCalculator_output_dir = "./Gencode_v25_Human_TCGA-BRCA_TPM_0"

    # TPMCalculator output suffix to process
    # It could be genes.out, genes.uni, genes.ent, transcript.out, transcripts.ent
    # Files can be compressed as the current example
    # The files are named: a59040e1-6d0b-49f1-b4b3-bd96b0e98536_sorted_genes.out.gz
    output_suffix = "_sorted_genes.out.gz"

    files = [ f for ds, df, files in os.walk(TPMCalculator_output_dir) for f in files if f.endswith(output_suffix)]

    data = pandas.DataFrame()
    i = 1
    for f in files:
        # Get sample name removing the suffix
        s = f.replace(output_suffix, '')
        print(str(i) + ' ' + f)
        df = pandas.read_csv(os.path.join(TPMCalculator_output_dir, f), sep='\t')
        df = df[['Gene_Id', 'Chr', 'Start', 'End', 'ExonLength', column]]
        df = df.rename(index=str, columns={column: s})
        if data.empty:
            data = df
        else:
            data = data.merge(df, on=['Gene_Id', 'Chr', 'Start', 'End', 'ExonLength'], how='outer')
        i += 1
    print('Data columns: ' + str(len(data.columns)))
    print('Data rows: ' + str(len(data)))
   
    # Printing a TSV file with all samples data
    data.to_csv(column + '.tsv', sep='\t', index=False, na_rep='0')
```

I will let you as soon as the new option is ready.

Thanks,
Roberto

**Comment by andreyurch** [comment]
Thank you very much, Roberto!

**Comment by r78v10a07** [comment]
New changes to the source code were made. The option -a will print all features (genes, transcripts, etc) no matter if they have reads assigned or no. 
Also, output features are sorted by chromosome using the same order in the GTF
