### ISSUE TITLE
ID with "#" in _genes.out file

### ISSUE THREAD

**Issue by xflicsu** [ncbi/TPMCalculator#33]
I use gtf file from Gencode database.
I found the TPMCalculator would prodeced two or more gene information of one gene id (ENSMUSG00000026162.7#1, ENSMUSG00000026162.7#2).
But the original id of gtf file is ENSMUSG00000026162.7.
Why TPMCalculator output two or more gene id with "#"?

**Comment by r78v10a07** [comment]
Hi,

The `#1` .. `#N` after gene name are copies of the same gene in different locations in the same chromosome. 

TPMCalculator define gene with copies as those genes with transcripts no overlapped in the same chromosome. Therefore, TPMCalculator reports read counts and TPM values for genes with copies in the same chromosome independently. 

The gene you're sending hast two transcripts no overlapping in chromosome 1.

https://useast.ensembl.org/Mus_musculus/Gene/Summary?g=ENSMUSG00000026162;r=1:74937222-75115283;db=core

Could you, please, send the line output for the *_gene.out file for this gene?

Thanks,
Roberto

**Comment by xflicsu** [comment]
ENSMUSG00000026162.7#1  chr1    74967138        75046638        79501   473     0.00715515      1053    240     0.267922        78448   240     1.19388 79501   473     0.0216868       1053    240     0.783729        78448   240           3.45299
ENSMUSG00000026162.7#2  chr1    75125135        75125199        65      2       0.0370038       65      2       0.0361695       0       0       0       65      2       0.112156        65      2       0.105803        0       0       0

> Hi,
> 
> The `#1` .. `#N` after gene name are copies of the same gene in different locations in the same chromosome.
> 
> TPMCalculator define gene with copies as those genes with transcripts no overlapped in the same chromosome. Therefore, TPMCalculator reports read counts and TPM values for genes with copies in the same chromosome independently.
> 
> The gene you're sending hast two transcripts no overlapping in chromosome 1.
> 
> https://useast.ensembl.org/Mus_musculus/Gene/Summary?g=ENSMUSG00000026162;r=1:74937222-75115283;db=core
> 
> Could you, please, send the line output for the *_gene.out file for this gene?
> 
> Thanks,
> Roberto

**Comment by r78v10a07** [comment]
Hi,
As expected, the transcripts no overlap each other, therefore, tagging the genes with copy number is the normal way TPMCalculator should work.
Thanks.
Roberto

**Comment by sunliang3361** [comment]
Hi, I have the same doubt here. 
Are ENSMUSG00000026162.7#1 and ENSMUSG00000026162.7#2 two transcripts of gene ENSMUSG00000026162.7? 
Are there any reasons why TMPcalculator doesn't merge the result together since it is gene output file (*_gene.out). or just give the transcript IDs and their corresponding TMP values? Thank you.

**Comment by r78v10a07** [comment]
Hi
The #1 .. #N after gene name are copies of the same gene in different locations in the same chromosome.

TPMCalculator define gene with copies as those genes with transcripts no overlapped in the same chromosome. Therefore, TPMCalculator reports read counts and TPM values for genes with copies in the same chromosome independently.

**Comment by sunliang3361** [comment]
Thank you for your response. This gene copies is specific to this sample or it's a general gene copies in GTF file? If it's specific to this sample, does that mean that TPMcalcular can detect gene copies?

**Comment by r78v10a07** [comment]
Hi,
The copies are specified in the GTF.
Roberto

From: "Liang Sun, Ph.D." ***@***.***>
Reply-To: ncbi/TPMCalculator ***@***.***>
Date: Thursday, May 27, 2021 at 9:50 AM
To: ncbi/TPMCalculator ***@***.***>
Cc: Roberto Vera Alvarez ***@***.***>, State change ***@***.***>
Subject: Re: [ncbi/TPMCalculator] ID with "#" in _genes.out file (#33)


Thank you for your response. This gene copies is specific to this sample or it's a general gene copies in GTF file? If it's specific to this sample, does that mean that TPMcalcular can detect gene copies?
