### ISSUE TITLE
Question on TPMCalculator : bam pre-treatment needed ?

### ISSUE THREAD

**Issue by LucoLab** [ncbi/TPMCalculator#42]
Do we need to index or sort the bam before using TPMCalculator ?

Thanks.

**Comment by r78v10a07** [comment]
Hi, sorted BAM file by chromosomic coordinates is required. The index no.

**Comment by LucoLab** [comment]
Is it throwing an error if not ?

**Comment by r78v10a07** [comment]
No, it is not. 
In principle, the sorted BAM file will be used only for improving performance as you will be processing the same chromosome. If it is not sorted, then the program will be changing chromosome pointers every time you process a read.
