### ISSUE TITLE
GTF error: "Key for isoform name was not found on GTF line"

### ISSUE THREAD

**Issue by nextjen92** [ncbi/TPMCalculator#47]
I am getting the following error when I try to run TPMcalculator: 
Key  for isoform name was not found on GTF line.
Error processing GTF line at Chromosome level:
scaffold11323   maker   exon    2123    2371    .       -       .       gene_ID "Ha_G028047"; transcript_ID "Ha_T028047_A"

My GTF doesn't have isoforms and I don't see a way to either specific an isoform key or skip it.

**Comment by r78v10a07** [comment]
Hi,
Could you share the GTF with me so I can have a better look?
It will also help if you share with me a BAM file aligned with this GTF.

**Comment by StromTroopers** [comment]
Hello, I'm getting the same kinf of issue: 

Here is a head of the gff file I used ;

```
NW_011887765.1	mmseqs2	exon	663068	666746	.	-	.	gene_id "gene1"
NW_011887825.1	mmseqs2	exon	469594	470107	.	-	.	gene_id "gene2
NW_011887765.1	mmseqs2	exon	646642	646945	.	+	.	gene_id "gene3
NW_011887825.1	mmseqs2	exon	465242	465473	.	+	.	gene_id "gene4"
```

and here is the error message I'm getting : 

```
Reading GTF file ... 
Key  for isoform name was not found on GTF line.
Error processing GTF line at Chromosome level:
NW_011887765.1	mmseqs2	exon	663068	666746	.	-	.	gene_id "gene1"
```

**Comment by r78v10a07** [comment]
Hi, try this annotation:

```text
NW_011887765.1	mmseqs2	exon	663068	666746	.	-	.	gene_id "gene1"; transcript_id "trans1"
NW_011887825.1	mmseqs2	exon	469594	470107	.	-	.	gene_id "gene2"; transcript_id "trans1"
NW_011887765.1	mmseqs2	exon	646642	646945	.	+	.	gene_id "gene3"; transcript_id "trans1"
NW_011887825.1	mmseqs2	exon	465242	465473	.	+	.	gene_id "gene4"; transcript_id "trans1"
```

This should solve the problem.

**Comment by StromTroopers** [comment]
Indeed it worked with this annotation thank you !
