### ISSUE TITLE
Pool BAM file and get TPM for each BAM experiment ? 

### ISSUE THREAD

**Issue by StromTroopers** [ncbi/TPMCalculator#53]
Hello, I have different BAM files wich corresponds do different tissue transcript sequencing reads. 
So my question is the following:

Is there a way to pool all the BAM file, get a **TPM** value for a list of specific genes (with coordinates), and to know if the genes are expressed globaly (pooled BAM) and (specificaly to certain tissues)? 

And also I wondered if TPMCalculator can calculate TPM values for genes but just with start/stop informations ? (I do not have any informations about exon/intron - my genes should be only exons since they are blast hits from a BLASTP analysis)

Thank you very much for your help

**Comment by r78v10a07** [comment]
Hi,
Regarding the pool BAM, you should run TPMCalculator for each BAM file independently. Then, you can create a matrix of raw reads or TPM for each gene and samples (BAM files) and use any of the available tools for differential gene expresion EdgeR or Deseq 

TPMCalculator should work with a custom GTF file. You can create or insert your "special" genes in a GTF as a single exon and everything should be processed correctly. Let me know if the program fails on this.

Best,
Roberto

**Comment by StromTroopers** [comment]
Hi, Ok I'm trying that I'll let you know 👍 

I had several other questions regarding the program : 

**1)** There is no threads option, does this mean that the program uses by default all threads available on the machine or only one/job? 

**2)** When giving a GFF file, does the program only evaluate the degree of expression of the given exons (from start to end) or does as **Stringtie** (if I'm not wrong) also gives other scaffold/contigs regions that have not been provided in the GFF file but are still expressed?

**Comment by StromTroopers** [comment]
Hello, I ran the program on only exon structures and it appears to work fine since I got the output files 👍 

mapping_SP1_transcripts.out
mapping_SP1_transcripts.ent
mapping_SP1_genes.uni
mapping_SP1_genes.out
mapping_SP1_genes.ent

So I wondered wich TPM value from wich file I should keep for my analysis since I only provided exon structures ? 

Here are the head of the results files: 

**mapping_SP1_transcripts.out**
```
Gene_Id	Transcript_Id	Chr	Start	End	Length	Reads	TPM	ExonLength	ExonReads	ExonTPM	IntronLength	IntronReads	IntronTPM
gene1	trans1	NW_011887765.1	646641	646944	304	489	68292	304	489	68292	0	0	0
gene2	trans1	NW_011887765.1	651602	654311	2710	653	10230.1	2710	653	10230.1	0	0	0
gene3	trans1	NW_011887765.1	663067	666745	3679	329	3796.65	3679	329	3796.65	0	0	0
```

**mapping_SP1_genes.ent**

```
Gene_Id	Chr	Type	Type_Number	start	end	Length	Reads	TPM
gene1	NW_011887765.1	exon	1	646641	646944	304	640	87065.3
gene2	NW_011887765.1	exon	1	651602	654311	2710	653	9965.12
gene3      NW_011887765.1	exon	1	663067	666745	3679	333	3743.29
```

**mapping_SP1_genes.uni**
```
Gene_Id	Chr	Type	Type_Number	start	end	Length	Reads	TPM
lef-4	NW_011887765.1	exon	1	646641	646944	304	640	87065.3
lef-8	NW_011887765.1	exon	1	651602	654311	2710	653	9965.12
helicase	NW_011887765.1	exon	1	663067	666745	3679	333	3743.29
```

(both .uni and .ent are the same here) 

**mapping_SP1_genes.out**
```
Gene_Id	Chr	Start	End	Length	Reads	TPM	ExonLength	ExonReads	ExonTPM	IntronLength	IntronReads	IntronTPM	UniqueLength	UniqueReads	UniqueTPM	UniqueExonL
ength	UniqueExonReads	UniqueExonTPM	UniqueIntronLength	UniqueIntronReads	UniqueIntronTPM
gene1	NW_011887765.1	646641	646944	304	640	87094.9	304	640	87094.9	0	0	0	304	640	87094.9	304	640	87094.9	0	0	0
gene2	NW_011887765.1	651602	654311	2710	653	9968.51	2710	653	9968.51	0	0	0	2710	653	9968.51	2710	653	9968.51	0	0	0
gene3	NW_011887765.1	663067	666745	3679	333	3744.56	3679	333	3744.56	0	0	0	3679	333	3744.56	3679	333	3744.56	0	0	0
```

**mapping_SP1_transcripts.ent**
```
Gene_Id	Transcript_Id	Chr	Type	Type_Number	start	end	Length	Reads	TPM
lef-4	trans1	NW_011887765.1	exon	1	646641	646944	304	489	68268.2
lef-8	trans1	NW_011887765.1	exon	1	651602	654311	2710	653	10226.5
helicase	trans1	NW_011887765.1	exon	1	663067	666745	3679	329	3795.33
```

**Comment by r78v10a07** [comment]
as you inserted your genes with one single exon, I think you should use the _genes.out values as they represent the TPM at gene level
