### ISSUE TITLE
libbamtools.so.2.4.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by StromTroopers** [ncbi/TPMCalculator#54]
Hello I'm using TPMcalculator on a cluster, so I installed the software with a BAMtools version installed in a conda environnement (during the installation it gave something like : 

**```
export BAMTOOLS_DIR=`/path1/mycondaenv/`
export CPPFLAGS="-I $BAMTOOLS_DIR/include/bamtools/"
export LDFLAGS="-L $BAMTOOLS_DIR/lib64 -Wl,-rpath,$BAMTOOLS_DIR/lib64"
```**

and then I simply  ran a  make, so the `/path1/TOOLS/TPMCalculator/bin/TPMCalculator` workes locally but when I try to run the program on a cluster I get the following error message : 

` /path1/TOOLS/TPMCalculator/bin/TPMCalculatorr: error while loading shared libraries: libbamtools.so.2.4.0: cannot open shared object file: No such file or directory`

Do you have an idea of what is going on ? 

Thank you for your help

**Comment by r78v10a07** [comment]
Are you installing TPMCalculator from Bioconda?

https://bioconda.github.io/recipes/tpmcalculator/README.html

That would be the easiest way to get it.

**Comment by StromTroopers** [comment]
Well I installed the git version because the bioconda version cannot be installed I get : 
```

conda install tpmcalculator
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

**Comment by StromTroopers** [comment]
Ok it was because it needed a python version below 3.7 (3.6 did work)

**Comment by r78v10a07** [comment]
Great!!
Let me know if you need anything else.
