### ISSUE TITLE
Chromosome with name: A01 does not exist

### ISSUE THREAD

**Issue by biozfxue** [ncbi/TPMCalculator#60]
My bam file comes from the STAR. When I run TPMCalculator, I received an error message: 
Reading GTF file ... 
Done in 0.19 seconds
Parsing sample: R500.Aligned.sortedByCoord.out.bam
Chromosome with name: A01 does not exist
Chromosome with name: A01 does not exist
Chromosome with name: A01 does not exist
Chromosome with name: A01 does not exist
Chromosome with name: A01 does not exist
Chromosome with name: A01 does not exist
...
Thanks for your help!

**Comment by r78v10a07** [comment]
Please, send the GTF you're using.

**Comment by biozfxue** [comment]
> Please, send the GTF you're using.

A01     Gmove   transcript      3870    5388    .       -       .       transcript_id "BraA01t00001Z"; gene_id "BraA01t00001Z";
A01     Gmove   CDS     3870    4225    .       -       2       transcript_id "BraA01t00001Z";
A01     Gmove   CDS     4609    4808    .       -       1       transcript_id "BraA01t00001Z";
A01     Gmove   CDS     4885    5017    .       -       2       transcript_id "BraA01t00001Z";
A01     Gmove   CDS     5130    5388    .       -       0       transcript_id "BraA01t00001Z";

**Comment by biozfxue** [comment]
> Please, send the GTF you're using.

I think I know where the problem is, I will try to fix my gtf file, but I also want to kown which version gtf would be best. They have different infornations.

**Comment by r78v10a07** [comment]
TPMCalculator works with "exon", you need to add the exons to your GTF
