### ISSUE TITLE
Gene number in input GTF differs from the TPMCalculator output

### ISSUE THREAD

**Issue by phlatphish** [ncbi/TPMCalculator#68]
My input GTF and the GFF from which it was derived contains 62417 genes.  I ran TPMCalculator on 15 BAM files corresponding to 15 RNA-seq experiments.  The number of lines in the file alignments.sorted.pos.uniq_genes.out differs in each case:

31124
33419
33888
34408
34876
36120
36162
36412
37151
37192
37521
38853
40305
40581
40760

There was a repeated message to STDERR saying:

Chromosome with name: XXXXXX does not exist

But I don't know its meaning or whether it is an error or a warning.

**Comment by dlandsman** [comment]
We’ll get back to you next week. The person working on this is on vacation at the moment.
David
=====================================
David Landsman, Ph.D.
Chief, Computational Biology Branch
 NCBI, NLM, NIH
Bethesda, Maryland, U.S.A.
=====================================
I will be teleworking between the hours of 9am and 5pm
but I might surprise you with a reply outside of those hours.

From: phlatphish ***@***.***>
Sent: Thursday, April 8, 2021 10:51 AM
To: ncbi/TPMCalculator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncbi/TPMCalculator] Gene number in input GTF differs from the TPMCalculator output (#68)


My input GTF and the GFF from which it was derived contains 62417 genes. I ran TPMCalculator on 15 BAM files corresponding to 15 RNA-seq experiments. The number of lines in the file alignments.sorted.pos.uniq_genes.out differs in each case:

31124
33419
33888
34408
34876
36120
36162
36412
37151
37192
37521
38853
40305
40581
40760

There was a repeated message to STDERR saying:

Chromosome with name: XXXXXX does not exist

But I don't know its meaning or whether it is an error or a warning.

**Comment by r78v10a07** [comment]
TPMCalculator by default prints only genes with read counts. If you would like all genes in the GTF you need to use the -a option.

> -a    Print out all features with read counts equal to zero. Default: No.

**Comment by phlatphish** [comment]
Got it, thanks. My bad. Will run it again.
-callum
