### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by tracychew** [ncbi/TPMCalculator#69]
Hi,

I installed TPMcalculator using conda. I have aligned FASTQs to GRCh38 with bowtie and have obtained GTF from Ensembl. I am not too sure what to make of this error - any help would be great, thanks.

Tracy

```
[tc6463@gadi-login-02 Scripts]$ /scratch/er01/apps/miniconda3/bin/TPMCalculator -g ../References/GRCh38_v103/Homo_sapiens.GRCh38.103.gtf -b ../RNA_cutadapt_min17_align_Coenen-Stass/HB10-aln-hg38.sorted.dedup.bam
Reading GTF file ...
Done in 163.879 seconds
Parsing sample: HB10-aln-hg38.sorted.dedup/scratch/er01/apps/miniconda3/bin/TPMCalculator: symbol lookup error: /scratch/er01/apps/miniconda3/bin/TPMCalculator: undefined symbol: _ZN8BamTools11SamSequenceC1ERKS0_
```

**Comment by dlandsman** [comment]
We’ll get back to you next week. The person working on this is on vacation at the moment.
David
=====================================
David Landsman, Ph.D.
Chief, Computational Biology Branch
 NCBI, NLM, NIH
Bethesda, Maryland, U.S.A.
=====================================
I will be teleworking between the hours of 9am and 5pm
but I might surprise you with a reply outside of those hours.

From: tracyc ***@***.***>
Sent: Wednesday, April 14, 2021 12:38 AM
To: ncbi/TPMCalculator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncbi/TPMCalculator] symbol lookup error (#69)


Hi,

I installed TPMcalculator using conda. I have aligned FASTQs to GRCh38 with bowtie and have obtained GTF from Ensembl. I am not too sure what to make of this error - any help would be great, thanks.

Tracy

***@***.*** Scripts]$ /scratch/er01/apps/miniconda3/bin/TPMCalculator -g ../References/GRCh38_v103/Homo_sapiens.GRCh38.103.gtf -b ../RNA_cutadapt_min17_align_Coenen-Stass/HB10-aln-hg38.sorted.dedup.bam

Reading GTF file ...

Done in 163.879 seconds

Parsing sample: HB10-aln-hg38.sorted.dedup/scratch/er01/apps/miniconda3/bin/TPMCalculator: symbol lookup error: /scratch/er01/apps/miniconda3/bin/TPMCalculator: undefined symbol: _ZN8BamTools11SamSequenceC1ERKS0_

**Comment by r78v10a07** [comment]
The error you're seeing is related to the BAMTools dynamic libraries tused by TPMCalculator. 
My guess is that you have a different BAMTools version installed in someplace and reachable via the LD_LIBRARY_PATH env variable.

Could you try this before running TPMCalculator?

```
export LD_LIBRARY_PATH=/scratch/er01/apps/miniconda3/lib/
```

**Comment by tracychew** [comment]
Hi, thanks for getting back to me! I'm still getting the same error:

```
[tc6463@gadi-login-07 Scripts]$ export LD_LIBRARY_PATH=/scratch/er01/apps/miniconda3/lib/
[tc6463@gadi-login-07 Scripts]$ echo $LD_LIBRARY_PATH
/scratch/er01/apps/miniconda3/lib/
[tc6463@gadi-login-07 Scripts]$ /scratch/er01/apps/miniconda3/bin/TPMCalculator -g ../References/GRCh38_v103/Homo_sapiens.GRCh38.103.gtf -b ../RNA_cutadapt_min17_align_Coenen-Stass/HB10-aln-hg38.sorted.dedup.bam
Reading GTF file ...
Done in 158.582 seconds
Parsing sample: HB10-aln-hg38.sorted.dedup/scratch/er01/apps/miniconda3/bin/TPMCalculator: symbol lookup error: /scratch/er01/apps/miniconda3/bin/TPMCalculator: undefined symbol: _ZN8BamTools11SamSequenceC1ERKS0_
```

**Comment by r78v10a07** [comment]
Hi,
Could you try to find the location of the libbamtools.so file?
You could try:

find /scratch/er01/apps/miniconda3/ -name libbamtools.so

**Comment by tracychew** [comment]
Hi, looks like I do have it in a couple locations including, I tried setting LB_LIBRARY_PATH to either location but I still get the same error:

`[tc6463@gadi-login-06 Scripts]$ find /scratch/er01/apps/miniconda3/ -name libbamtools.so
/scratch/er01/apps/miniconda3/pkgs/bamtools-2.5.1-h9a82719_8/lib/libbamtools.so
find: '/scratch/er01/apps/miniconda3/pkgs/urllib3-1.25.8-py37_0fgotlour': Permission denied
find: '/scratch/er01/apps/miniconda3/pkgs/urllib3-1.25.8-py37_077kc6tii': Permission denied
find: '/scratch/er01/apps/miniconda3/pkgs/libgcc-ng-9.1.0-hdf63c60_0zi7updp_': Permission denied
find: '/scratch/er01/apps/miniconda3/pkgs/xz-5.2.4-h14c3975_45xw96xfv': Permission denied
/scratch/er01/apps/miniconda3/lib/libbamtools.so
[tc6463@gadi-login-06 Scripts]$ export LD_LIBRARY_PATH=/scratch/er01/apps/miniconda3/lib/
[tc6463@gadi-login-06 Scripts]$ /scratch/er01/apps/miniconda3/bin/TPMCalculator -g ../References/GRCh38_v103/Homo_sapiens.GRCh38.103.gtf -b ../RNA_cutadapt_min17_align_Coenen-Stass/HB10-aln-hg38.sorted.dedup.bam
Reading GTF file ...
Done in 162.429 seconds
Parsing sample: HB10-aln-hg38.sorted.dedup/scratch/er01/apps/miniconda3/bin/TPMCalculator: symbol lookup error: /scratch/er01/apps/miniconda3/bin/TPMCalculator: undefined symbol: _ZN8BamTools11SamSequenceC1ERKS0_
[tc6463@gadi-login-06 Scripts]$ export LD_LIBRARY_PATH=^C
[tc6463@gadi-login-06 Scripts]$ export LD_LIBRARY_PATH=/scratch/er01/apps/miniconda3/pkgs/bamtools-2.5.1-h9a82719_8/lib                                  [tc6463@gadi-login-06 Scripts]$ /scratch/er01/apps/miniconda3/bin/TPMCalculator -g ../References/GRCh38_v103/Homo_sapiens.GRCh38.103.gtf -b ../RNA_cutadapt_min17_align_Coenen-Stass/HB10-aln-hg38.sorted.dedup.bam
Reading GTF file ...
Done in 161.304 seconds
Parsing sample: HB10-aln-hg38.sorted.dedup/scratch/er01/apps/miniconda3/bin/TPMCalculator: symbol lookup error: /scratch/er01/apps/miniconda3/bin/TPMCalculator: undefined symbol: _ZN8BamTools11SamSequenceC1ERKS0_
`

**Comment by r78v10a07** [comment]
Hi, please, export the LD_LIBRARY_PATH like this:

```
export LD_LIBRARY_PATH=/scratch/er01/apps/miniconda3/pkgs/bamtools-2.5.1-h9a82719_8/lib/
```

**Comment by tracychew** [comment]
I tried that in the past, I tried it again and figured out the issue now that I know bamtools was the problem, thanks!

I had to git clone TPMCalculator in the directory where BAMTools was compiled and installed (instead of a separate directory - how we would normally structure tool installs) 

[tc6463@gadi-login-03 TPMCalculator]$ make
"make" -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/scratch/er01/apps/TPMCalculator'
"make"  -f nbproject/Makefile-Release.mk bin/TPMCalculator
make[2]: Entering directory '/scratch/er01/apps/TPMCalculator'
mkdir -p build/Release/GNU-MacOSX/src
rm -f "build/Release/GNU-MacOSX/src/DiffExpIR.o.d"
g++ -g   -c -O2 -Iincludes -I../../bamtools/include/bamtools -std=c++14 -MMD -MP -MF "build/Release/GNU-MacOSX/src/DiffExpIR.o.d" -o build/Release/GNU-MacOSX/src/DiffExpIR.o src/DiffExpIR.cpp
src/DiffExpIR.cpp:26:10: fatal error: api/BamReader.h: No such file or directory
 #include "api/BamReader.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [nbproject/Makefile-Release.mk:94: build/Release/GNU-MacOSX/src/DiffExpIR.o] Error 1
make[2]: Leaving directory '/scratch/er01/apps/TPMCalculator'
make[1]: *** [nbproject/Makefile-Release.mk:85: .build-conf] Error 2
make[1]: Leaving directory '/scratch/er01/apps/TPMCalculator'
make: *** [nbproject/Makefile-impl.mk:40: .build-impl] Error 2

**Comment by r78v10a07** [comment]
Is this solved?

**Comment by tracychew** [comment]
Yes, thank you :)
