### ISSUE TITLE
Sets the name of the output

### ISSUE THREAD

**Issue by leeyw2021** [ncbi/TPMCalculator#70]
How could I set the name of the output and specify full path for the output in TPMCalculator tool?

**Comment by dlandsman** [comment]
We’ll get back to you next week. The person working on this is on vacation at the moment.
David

=====================================
David Landsman, Ph.D.
Chief, Computational Biology Branch
 NCBI, NLM, NIH
Bethesda, Maryland, U.S.A.
=====================================
I will be teleworking between the hours of 9am and 5pm
but I might surprise you with a reply outside of those hours.

From: leeyw2021 ***@***.***>
Sent: Thursday, April 15, 2021 5:14 AM
To: ncbi/TPMCalculator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncbi/TPMCalculator] Sets the name of the output (#70)


How could I set the name of the output and specify full path for the output in TPMCalculator tool?

**Comment by r78v10a07** [comment]
Unfortunately, the current version of TPMCalculator takes the output name from the BAM file it is processing. The BAM extension is removed and the TPMCalculator suffixes are added.
I will add to our development plans a new feature to set an output directory.
