### ISSUE TITLE
For the paired end reads, is it recommended to use option -p or should i go with default without it?

### ISSUE THREAD

**Issue by unique379r** [ncbi/TPMCalculator#72]
Hi
I need to have tpm counts for paired end reads mapped with star, should i use option -p (Use only properly paired reads. Default: No. Recommended for paired-end reads.) or by default without it ? whats pros and cons os using it ?

Thanks

**Comment by r78v10a07** [comment]
Hi,
-p option will make TPMCalculator count only properly paired reads. This mean reads aligned to the same chromosome. 
I would recommend use it for RNA-Seq quantification of paired-end samples. I also would filter by MAPQ using the -q option. In your case, as you are using STAR, I would quantify only unique and properly paired reads for that you need to use the options: -q 255 -p
