### ISSUE TITLE
Output file description

### ISSUE THREAD

**Issue by tracychew** [ncbi/TPMCalculator#73]
Hi, I used TPMCalculator release 0.0.4 and the outputs don't quite match the descriptions on the [wiki](https://github.com/ncbi/TPMCalculator/wiki/Output-files), could you please clarify what the outputs are? 

My command:
```
TPMCalculator -a -p \
        -q 255 \
        -g ${gtf} \
        -b ${bam} 
```

I get 3 output files per BAM, e.g. Control_1.final_genes.out, Control_1.final_genes.ent, Control_1.final_genes.uni

`final_genes.out` seems to match the first output file described, headers are a little different:

Gene_Id Chr     Start   End     Length  Reads   TPM     ExonLength      ExonReads       ExonTPM IntronLength    IntronReads     IntronTPM       UniqueLength        UniqueReads     UniqueTPM       UniqueExonLength        UniqueExonReads UniqueExonTPM   UniqueIntronLength      UniqueIntronReads  UniqueIntronTPM

The `_genes.ent` file and `_genes.uni` files have these headers - what are the differences and where could I find transcript ID?
Gene_Id Chr     Type    Type_Number     start   end     Length  Reads   TPM

Thanks

**Comment by Souzavgp** [comment]
Hello, in the supplementary material of the article you can find that answer.

_genes.out Include calculated values per Gene

_genes.uni Include calculated values per non-overlapped features per Gene

_genes.ent Include calculated values for all features per Gene

article: https://academic.oup.com/bioinformatics/article/35/11/1960/5150437

**Comment by r78v10a07** [comment]
@Souzavgp is right. Thanks for helping.
