### ISSUE TITLE
/usr/bin/ld: cannot find -lbamtools

### ISSUE THREAD

**Issue by xiaocong3333** [ncbi/TPMCalculator#74]
Hi there,

I installed the BamTools and TPMCalculateor, but when I use make in the TPMCalulator fold, it reported some errors, as below:

"make" -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/congxiao/software/TPMCalculator-master'
"make"  -f nbproject/Makefile-Release.mk bin/TPMCalculator
make[2]: Entering directory '/home/congxiao/software/TPMCalculator-master'
mkdir -p bin
g++ -g -I /home/congxiao/software/bamtools/include/bamtools/ -L /home/congxiao/software/bamtools/lib64 -Wl,-rpath,/home/congxiao/software/bamtools/lib64  -o bin/TPMCalculator build/Release/GNU-MacOSX/src/DiffExpIR.o build/Release/GNU-MacOSX/src/FastaFactory.o build/Release/GNU-MacOSX/src/RandomFactory.o build/Release/GNU-MacOSX/src/ReadFactory.o build/Release/GNU-MacOSX/src/Stats.o build/Release/GNU-MacOSX/src/TextParser.o build/Release/GNU-MacOSX/src/bd0.o build/Release/GNU-MacOSX/src/bratio.o build/Release/GNU-MacOSX/src/bstring.o build/Release/GNU-MacOSX/src/chebyshev.o build/Release/GNU-MacOSX/src/choose.o build/Release/GNU-MacOSX/src/dnorm.o build/Release/GNU-MacOSX/src/dt.o build/Release/GNU-MacOSX/src/gamma.o build/Release/GNU-MacOSX/src/lbeta.o build/Release/GNU-MacOSX/src/lgamma.o build/Release/GNU-MacOSX/src/lgammacor.o build/Release/GNU-MacOSX/src/main.o build/Release/GNU-MacOSX/src/pbeta.o build/Release/GNU-MacOSX/src/phyper.o build/Release/GNU-MacOSX/src/pnorm.o build/Release/GNU-MacOSX/src/pt.o build/Release/GNU-MacOSX/src/qnorm.o build/Release/GNU-MacOSX/src/qt.o build/Release/GNU-MacOSX/src/stirlerr.o build/Release/GNU-MacOSX/src/sunif.o build/Release/GNU-MacOSX/src/wilcox.o -L../../bamtools/lib -lbamtools -lm -lz
/usr/bin/ld: cannot find -lbamtools
collect2: error: ld returned 1 exit status
make[2]: *** [nbproject/Makefile-Release.mk:89: bin/TPMCalculator] Error 1
make[2]: Leaving directory '/home/congxiao/software/TPMCalculator-master'
make[1]: *** [nbproject/Makefile-Release.mk:85: .build-conf] Error 2
make[1]: Leaving directory '/home/congxiao/software/TPMCalculator-master'
make: *** [nbproject/Makefile-impl.mk:40: .build-impl] Error 2

I installed the bamtools just as your README file, I don't know why.

Thank you!

**Comment by r78v10a07** [comment]
Hi,
Could you, please, check if this path exists in your computer:

/home/congxiao/software/bamtools/lib64

Sometimes, depending on the host OS, the bamtools library is installed in *lib* instead of *lib64*

Thanks.
