### ISSUE TITLE
No TPM values, no reads processed 

### ISSUE THREAD

**Issue by marco91sol** [ncbi/TPMCalculator#79]
Hi, 

I am using TPMCalculator using the following command: 

TPMCalculator -g file.gtf -d ./ -a -p -e 

In the current directory, I have sorted bam files deriving from HISAT2 alignment tool of RNA reads against the genome. 

Here, you will find the head of samtools view on bam file.
![image](https://user-images.githubusercontent.com/42739946/170988264-b268bd7b-8eb4-4eef-8141-11d3cc4bbdfa.png)

Here, follows part of the log file: 

Reading GTF file ...
Done in 12.0684 seconds
Parsing sample: trimmed_hisat_out.bam.sorted
 0 reads processed in 23.4511 seconds
Printing results
Total time: 42.3443 seconds

Thanks for the support!

Br,
Marco

**Comment by pongorlorinc** [comment]
Hi Maco,

I see you have a single-end BAM file, but using paired-end mode for
quantification.

Could you try removing the "-p" flag? It should work then.

Best wishes
Lorinc

**Comment by pongorlorinc** [comment]
Hmmm, it means that there is a mismatch of chromosomes between the gtf and
bam file.

Did you use the same gtf during alignment?

**Comment by pongorlorinc** [comment]
What error do you get with this other bam file?

**Comment by marco91sol** [comment]
No error. It only gives me this as output:
"""
Reading GTF file ...
Done in 6.53447 seconds
Parsing BAM files
0 reads processed in 9.5e-05 seconds
Printing results
Total time: 6.53495 seconds"""

**Comment by marco91sol** [comment]
At the moment, It's working... There were some issues with the **samtools sort** command. 

However, It provides the usual mistake " Chromosome with name: NW_020844013.1 does not exist".
Neverthless it worked before even giving that mistake.

Thanks for the support!

Best regards,
Marco

**Comment by pongorlorinc** [comment]
Glad to hear it!
