### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sdash-github** [ncbi/TPMCalculator#8]
Need some documentation on how to use it, how to install it, etc.

**Comment by r78v10a07** [comment]
Please, have a look at this Wiki page:
https://github.com/ncbi/TPMCalculator/wiki/TPMCalculator

Let me know if you need more info.

**Comment by r78v10a07** [comment]
I've added a more organized documentation.
https://github.com/ncbi/TPMCalculator/wiki
