### ISSUE TITLE
Build problems on Ubuntu and MacOSX

### ISSUE THREAD

**Issue by peterstockwell** [ncbi/TPMCalculator#86]
Following the README instructions for building TPMCalculator from source fails for a couple of reasons:

1: setting LDFLAGS="-L $BAMTOOLS_DIR/lib64 -Wl,-rpath,$BAMTOOLS_DIR/lib64"
 is not correct - the build process for bamtools does not generate a lib64 directory, rather
libbamtools.a is in the lib directory.

2: the TPMCalculator make fails since the final build command contains -L../../bamtools/lib
whereas the instructions have the default dir as /TPMCalculator from where the command
should be -L../bamtools/lib.

**Comment by r78v10a07** [comment]
Hi @peterstockwell, thanks for reporting this. You're right, we define a location for BAMtools library in `lib64` but this change in some linux distributions or other OS. You can edit the Makefile to adjust in your case.
