### ISSUE TITLE
After installing version 0.0.4, -version still prints 0.0.3

### ISSUE THREAD

**Issue by vmkalbskopf** [ncbi/TPMCalculator#88]
I installed TPMCalculator using conda from the bioconda channel
`mamba install tpmcalculator=0.0.4`

However:
```
TPMCalculator -version
Version: 0.0.3
```

**Comment by r78v10a07** [comment]
Thanks for reporting this. I published a new version 0.0.4.1 with that bug fixed.
We need to wait for bioconda to bump the version on their own.
